### ISSUE TITLE
스터디 같이 하실 분 코멘트 남겨주세요!

### ISSUE THREAD

**Issue by 21kyu** [21kyu/study-guam#1]

**Comment by bjl6991** [comment]
같이 하면서 저 때문에 많이 답답할 수 있겠지만 받아주셔서 정말 감사합니다 정말 열심히 하겠습니다

**Comment by waahhh** [comment]
안녕하세요. 구경꾼 입니다. **스터티괌을 추천합니다.**

**Comment by w-beom** [comment]
사랑합니다

**Comment by Sorgfalt** [comment]
안녕하세요 현재 스프링 부트 공부 중인데 스터디 같이 하고 싶어서 코멘트 남깁니다
스프링 부트를 처음 공부하는거라 잘 하지는 못 하지만 열심히 스터디에 참여하고 싶습니다

**Comment by BaekSeungYeol** [comment]
안녕하세요 단톡방 공고보고 문의드립니다! Devops에 관심이 생겨서 열심히 해보고 싶습니다. 잘하진 못하지만 끈기있게 할 수 있습니다!

**Comment by AhKong** [comment]
안녕하세요! 단톡방 공지 보고 스터디 참여하고 싶어서 코멘트 남깁니다! ☺️☺️   열심히 할 수 있습니다 !

**Comment by abcdsds** [comment]
참여합니다 kimmunki 입니다.

**Comment by OriginalKimChi** [comment]
안녕하세요 devops에 관심 많은 주니어 개발자입니다. 해당 스터디가 제가 공부하고 싶은 주제와 일치해서  참여하고 싶습니다! 잘부탁드립니다~

**Comment by gcha-kim** [comment]
안녕하세요 참석해보고싶습니다 그냥 코멘트만 남기면될까요?

**Comment by loop-study** [comment]
안녕하세요 톡방 공지보고 왔습니다. 참여하고 싶네요.

**Comment by 21kyu** [comment]
헐 뭐지 벌써 저 포함 10명이네요!
이정도로 모집은 마감하고 진행하면 될 것 같습니다.
첫번째 주제가 준비되면 방 파서 말씀드릴게요. 그 때 이것저것 정해봐요. 주말쯤 예상해주시면 감사하겠습니다.

**Comment by 21kyu** [comment]
빠른 커뮤니케이션을 위해 오픈톡방을 만들었어요.
https://open.kakao.com/o/gMz87fUc
